version: ~> 1

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

script:
  - bundle exec rake
  - gem build travis.gemspec
  - gem install travis-*.gem
  - APPMAP=true bundle exec rspec spec

after_script:
- env DEBUG=true ruby ./upload-appmaps tmp/appmap/rspec

